packages:
  - packages/*

allowBuilds:
  "@scarf/scarf": false
  "@swc/core": false
  "@tree-sitter-grammars/tree-sitter-yaml": false
  core-js-pure: false
  esbuild: false
  protobufjs: false
  sharp: false
  tree-sitter: false
  tree-sitter-json: false

patchedDependencies:
  "@phosphor-icons/react@2.1.10": patches/@phosphor-icons__react@2.1.10.patch
