/**
 * Stub emitter — produces IR JSON output for Phase 1 pipeline testing.
 *
 * This is a placeholder emitter that serializes DotIR as formatted JSON.
 * Phase 2 (Swift) and Phase 3 (Compose) will provide real emitters.
 */

import type { DotIR } from './ir';
import type { DotEmitter, CodegenTarget } from './emitter';

export class StubEmitter implements DotEmitter {
  readonly target: CodegenTarget;
  private fragments: string[] = [];

  constructor(target: CodegenTarget) {
    this.target = target;
  }

  emit(ir: DotIR): string {
    const fragment = JSON.stringify(ir, null, 2);
    this.fragments.push(fragment);
    return fragment;
  }

  finalize(moduleName: string): string {
    const header = [
      `// ${moduleName} — Generated by dot codegen (target: ${this.target})`,
      `// Do not edit manually. Regenerate with: dot-codegen --target ${this.target}`,
      '',
    ].join('\n');

    return header + '[\n' + this.fragments.join(',\n') + '\n]\n';
  }
}
