import {
  // Navigation & UI
  Home,
  Menu,
  X,
  Search,
  Settings,
  User,
  Bell,
  Heart,
  Star,
  Bookmark,
  Share,
  Download,
  Upload,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  AlertCircle,
  Info,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  
  // Communication & Social
  MessageCircle,
  Phone,
  Mail,
  Send,
  Reply,
  Forward,
  Copy,
  Link,
  ExternalLink,
  
  // Media & Entertainment
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Volume2,
  VolumeX,
  Music,
  Video,
  Image,
  Camera,
  Mic,
  Headphones,
  
  // Emotion & Expression
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  ThumbsUp,
  ThumbsDown,
  
  // Data & Analytics
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  FileText,
  Folder,
  Calendar,
  Clock,
  Timer,
  
  // Status & Feedback
  Loader2,
  RefreshCw,
  CheckCircle,
  XCircle,
  HelpCircle,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  Zap,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  
  // Finance & E-commerce
  CreditCard,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Store,
  Tag,
  Percent,
  Calculator,
  Receipt,
  Wallet,
  PiggyBank,
  BarChart,
  LineChart,
  
  // Mobile & App
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Wifi,
  WifiOff,
  Bluetooth,
  Signal,
  Battery,
  BatteryCharging,
  Volume,
  Volume1,
  Vibrate,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  // Fullscreen,
  
  // Business & Productivity
  Briefcase,
  Building,
  Building2,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UserCog,
  // UserSearch,
  
  // Files & Documents
  File,
  FileText as FileTextIcon,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileCode,
  FileSpreadsheet,
  FileCheck,
  FileX,
  FilePlus,
  FileMinus,
  FileEdit,
  FileSearch,
  
  // Security & Privacy
  Shield as ShieldIcon,
  ShieldCheck,
  // ShieldX,
  ShieldAlert,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key,
  Fingerprint,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  
  // Communication Extended
  MessageSquare,
  MessageCircle as MessageCircleIcon,
  Phone as PhoneIcon,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  PhoneMissed,
  PhoneOff,
  Mail as MailIcon,
  MailOpen,
  MailCheck,
  MailX,
  MailPlus,
  MailMinus,
  MailSearch,
  
  // Social Media
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  Twitch,
  Github,
  Gitlab,
  Slack,
  
  // Navigation Extended
  Map,
  MapPin,
  Navigation,
  Navigation2,
  Compass,
  Globe,
  Globe2,
  Flag,
  FlagTriangleRight,
  Home as HomeIcon,
  Building as BuildingIcon,
  Store as StoreIcon,
  
  // Actions Extended
  Save,
  SaveAll,
  Undo,
  Redo,
  Scissors,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  ListChecks,
  
  // Feedback Extended
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Heart as HeartIcon,
  HeartOff,
  Star as StarIcon,
  StarOff,
  Bookmark as BookmarkIcon,
  BookmarkPlus,
  BookmarkMinus,
  // BookmarkX,
  
  // Status Extended
  CheckCircle as CheckCircleIcon,
  XCircle as XCircleIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  Info as InfoIcon,
  HelpCircle as HelpCircleIcon,
  Circle,
  CircleDot,
  CircleSlash,
  
  // Weather Extended
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  CloudRain as CloudRainIcon,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  
  // Time & Date
  Clock as ClockIcon,
  Timer as TimerIcon,
  Calendar as CalendarIcon,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarClock,
  
  // TypeScript types
  LucideIcon,
  
  // 추가된 누락 아이콘들
  Palette,
  BookOpen,
  Layers,
  MousePointer,
  ToggleLeft,
  Square,
  Sidebar,
  Gauge,
  Sparkles,
} from 'lucide-react'

// 아이콘 매핑 객체
export const icons: Record<string, LucideIcon> = {
  // Navigation & UI
  home: Home,
  menu: Menu,
  close: X,
  search: Search,
  settings: Settings,
  user: User,
  bell: Bell,
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  share: Share,
  download: Download,
  upload: Upload,
  edit: Edit,
  delete: Trash2,
  add: Plus,
  remove: Minus,
  check: Check,
  alert: AlertCircle,
  info: Info,
  warning: AlertTriangle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  
  // Communication & Social
  message: MessageCircle,
  phone: Phone,
  mail: Mail,
  send: Send,
  reply: Reply,
  forward: Forward,
  copy: Copy,
  link: Link,
  externalLink: ExternalLink,
  
  // Media & Entertainment
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  volume: Volume2,
  mute: VolumeX,
  music: Music,
  video: Video,
  image: Image,
  camera: Camera,
  mic: Mic,
  headphones: Headphones,
  
  // Emotion & Expression
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
  angry: Angry,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  
  // Data & Analytics
  chart: BarChart3,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: Activity,
  database: Database,
  file: FileText,
  folder: Folder,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  
  // Status & Feedback
  loader: Loader2,
  refresh: RefreshCw,
  success: CheckCircle,
  error: XCircle,
  help: HelpCircle,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  rain: CloudRain,
  
  // Finance & E-commerce
  creditCard: CreditCard,
  dollarSign: DollarSign,
  euro: Euro,
  poundSterling: PoundSterling,
  bitcoin: Bitcoin,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  package: Package,
  truck: Truck,
  store: Store,
  tag: Tag,
  percent: Percent,
  calculator: Calculator,
  receipt: Receipt,
  wallet: Wallet,
  piggyBank: PiggyBank,
  barChart: BarChart,
  lineChart: LineChart,
  
  // Mobile & App
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  laptop: Laptop,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  signal: Signal,
  battery: Battery,
  batteryCharging: BatteryCharging,
  volume1: Volume1,
  vibrate: Vibrate,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  maximize: Maximize,
  minimize: Minimize,
  // fullscreen: Fullscreen,
  
  // Business & Productivity
  briefcase: Briefcase,
  building: Building,
  building2: Building2,
  users: Users,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userX: UserX,
  userCog: UserCog,
  // userSearch: UserSearch,
  
  // Files & Documents
  fileText: FileTextIcon,
  fileImage: FileImage,
  fileVideo: FileVideo,
  fileAudio: FileAudio,
  fileArchive: FileArchive,
  fileCode: FileCode,
  fileSpreadsheet: FileSpreadsheet,
  fileCheck: FileCheck,
  fileX: FileX,
  filePlus: FilePlus,
  fileMinus: FileMinus,
  fileEdit: FileEdit,
  fileSearch: FileSearch,
  
  // Security & Privacy
  shieldCheck: ShieldCheck,
  // shieldX: ShieldX,
  shieldAlert: ShieldAlert,
  key: Key,
  fingerprint: Fingerprint,
  
  // Communication Extended
  messageSquare: MessageSquare,
  messageCircle: MessageCircleIcon,
  phoneCall: PhoneCall,
  phoneIncoming: PhoneIncoming,
  phoneOutgoing: PhoneOutgoing,
  phoneMissed: PhoneMissed,
  phoneOff: PhoneOff,
  mailOpen: MailOpen,
  mailCheck: MailCheck,
  mailX: MailX,
  mailPlus: MailPlus,
  mailMinus: MailMinus,
  mailSearch: MailSearch,
  
  // Social Media
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  youtube: Youtube,
  twitch: Twitch,
  github: Github,
  gitlab: Gitlab,
  slack: Slack,
  
  // Navigation Extended
  map: Map,
  mapPin: MapPin,
  navigation: Navigation,
  navigation2: Navigation2,
  compass: Compass,
  globe: Globe,
  globe2: Globe2,
  flag: Flag,
  flagTriangleRight: FlagTriangleRight,
  
  // Actions Extended
  save: Save,
  saveAll: SaveAll,
  undo: Undo,
  redo: Redo,
  scissors: Scissors,
  type: Type,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  list: List,
  listOrdered: ListOrdered,
  listChecks: ListChecks,
  
  // Feedback Extended
  heartOff: HeartOff,
  starOff: StarOff,
  bookmarkPlus: BookmarkPlus,
  bookmarkMinus: BookmarkMinus,
  // bookmarkX: BookmarkX,
  
  // Status Extended
  circle: Circle,
  circleDot: CircleDot,
  circleSlash: CircleSlash,
  
  // Weather Extended
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  cloudFog: CloudFog,
  wind: Wind,
  thermometer: Thermometer,
  droplets: Droplets,
  umbrella: Umbrella,
  
  // Time & Date
  calendarDays: CalendarDays,
  calendarCheck: CalendarCheck,
  calendarX: CalendarX,
  calendarPlus: CalendarPlus,
  calendarMinus: CalendarMinus,
  calendarClock: CalendarClock,
  
  // 추가된 누락 아이콘들
  palette: Palette,
  bookOpen: BookOpen,
  layers: Layers,
  mousePointer: MousePointer,
  toggleLeft: ToggleLeft,
  square: Square,
  sidebar: Sidebar,
  gauge: Gauge,
  sparkles: Sparkles,
}

// 아이콘 이름 타입
export type IconName = keyof typeof icons

// 아이콘 카테고리별 그룹화
export const iconCategories = {
  navigation: ['home', 'menu', 'close', 'search', 'settings', 'user', 'bell', 'map', 'mapPin', 'navigation', 'compass', 'globe', 'flag', 'sidebar'],
  actions: ['edit', 'delete', 'add', 'remove', 'check', 'share', 'download', 'upload', 'save', 'undo', 'redo', 'copy', 'scissors', 'mousePointer', 'toggleLeft'],
  communication: ['message', 'phone', 'mail', 'send', 'reply', 'forward', 'messageSquare', 'phoneCall', 'mailOpen'],
  media: ['play', 'pause', 'skipBack', 'skipForward', 'volume', 'mute', 'music', 'video', 'image', 'camera', 'mic', 'headphones'],
  emotions: ['smile', 'frown', 'meh', 'laugh', 'angry'],
  feedback: ['thumbsUp', 'thumbsDown', 'success', 'error', 'warning', 'info', 'heart', 'star', 'bookmark'],
  data: ['chart', 'pieChart', 'trendingUp', 'trendingDown', 'activity', 'database', 'barChart', 'lineChart'],
  status: ['loader', 'refresh', 'lock', 'unlock', 'eye', 'eyeOff', 'shield', 'battery', 'wifi'],
  weather: ['sun', 'moon', 'cloud', 'rain', 'cloudSnow', 'cloudLightning', 'wind', 'thermometer'],
  finance: ['creditCard', 'dollarSign', 'euro', 'poundSterling', 'bitcoin', 'shoppingCart', 'wallet', 'calculator'],
  business: ['briefcase', 'building', 'users', 'userPlus', 'userCheck', 'userCog'],
  files: ['fileText', 'fileImage', 'fileVideo', 'folder', 'fileCheck', 'bookOpen'],
  social: ['facebook', 'twitter', 'instagram', 'linkedin', 'youtube', 'github', 'slack'],
  mobile: ['smartphone', 'tablet', 'monitor', 'laptop', 'bluetooth', 'signal', 'fullscreen'],
  editing: ['type', 'bold', 'italic', 'underline', 'alignLeft', 'alignCenter', 'list', 'listOrdered', 'palette', 'layers', 'square'],
  time: ['clock', 'timer', 'calendar', 'calendarDays', 'calendarCheck', 'calendarClock'],
} as const

// 감정별 아이콘 매핑
export const emotionIcons = {
  happy: 'smile',
  sad: 'frown',
  neutral: 'meh',
  excited: 'laugh',
  angry: 'angry',
  love: 'heart',
  like: 'thumbsUp',
  dislike: 'thumbsDown',
} as const

// 상태별 아이콘 매핑
export const statusIcons = {
  loading: 'loader',
  success: 'success',
  error: 'error',
  warning: 'warning',
  info: 'info',
  locked: 'lock',
  unlocked: 'unlock',
  visible: 'eye',
  hidden: 'eyeOff',
} as const 